### PR TITLE
Initial map, user, and status functionality

### PR DESCRIPTION
**Pull request by jlaurentpdx**
- Fixed Map navigation issue caused by deprecated `onViewportChange`; replaced by `onMove`
-- BUG: A `setState` inside `onMove` occasionally causes App to crash with 'Maximum update depth exceeded' error.
- Navigation controls appear in top-right corner of Map
- User can opt-in to location with `GeolocateControl`, toggle button in top-right corner of screen
- User coordinates are stored into state for future use
- Popup renders at user's location once coordinates appear in state

### CODE REVIEW

**Review by baileykue — APPROVED** [review]
looks great!

**Review by VioletKatrinStewart — APPROVED** [review]

**Review by VioletKatrinStewart — APPROVED** [review]

**Review by baileykue — COMMENTED** [review]
incredible! yay for components

**Review by spencer-eagleton — APPROVED** [review]
love that

**Review by baileykue — APPROVED** [review]
*thumbs up*

**Pull request merged**
